export const matchupActionTypes = {
  ADD_YOUR_POKEMON: "ADD_YOUR_POKEMON",
  CHANGE_YOUR_POKEMON: "CHANGE_YOUR_POKEMON",
  REMOVE_YOUR_POKEMON: "REMOVE_YOUR_POKEMON",
  ADD_OPPONENT_POKEMON: "ADD_OPPONENT_POKEMON",
  CHANGE_OPPONENT_POKEMON: "CHANGE_OPPONENT_POKEMON",
  REMOVE_OPPONENT_POKEMON: "REMOVE_OPPONENT_POKEMON",
};
